### ISSUE TITLE
Change repo description

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/workshop-choo#14]
It's currently:

```
Learn the TCBY stack through a set of exercises
```

For those of us familiar with the "TCBY stack" term, I think the current description makes sense, but for folks who may come to this repo from choo, or see it starred in their feed by someone, it's a little cryptic. Perhaps:

```
Learn the choo framework through a set of exercises
```

**Comment by yoshuawuyts** [comment]
Changed it! :sparkles:
