### ISSUE TITLE
QA: first app

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/workshop-choo#15]
currently guiding my friend through the first chapter; posting feedback here was we go:
- [ ] explain they should create a new directory for the project so that it's scoped; probs recommend `src/$github-username/my-first-choo-project` or smth
- [ ] installing `choo` is apparently hard; perhaps mention `npm init --yes` and `npm install --save choo`

**Comment by timwis** [comment]
Hey @yoshuawuyts did your friend see the **Boilerplate** section at the top? Or is that not clear enough? I just added `--yes` to the `npm init` instructions (previously it said "default settings are fine"), so hopefully that will make it more clear.

**Comment by yoshuawuyts** [comment]
Hah, yeah I reckon they skipped over it - def think `--yes` might make it easier to setup. Thanks heaps for doing all this hey :D
