### ISSUE TITLE
Sup, choo bug?

### ISSUE THREAD

**Issue by sospedra** [yoshuawuyts/workshop-choo#24]
Hi, I was doing the `sup, choo` tutorial. Copied word by word and I get this error:

```
Uncaught TypeError: Cannot read property '0' of undefined
    walk @ index.js:26
    sheetRouter @ index.js:48 
    createRouter @ index.js:123
    start @ index.js:70
    7.choo @ client.js [sm]:12
    s @ _prelude.js:1
    e @ _prelude.js:1
    (anonymous function) @ _prelude.js:
```

This is, currently, my `client.js`. Maybe I fucked something, but again. At the end, I literally copied:

```
const choo = require('choo')
const html = require('choo/html')

const app = choo()
const sexyView = () => html`
  <div>Hello chooters</div>
`

app.router((route) => {
  route('/', sexyView)
})

const tree = app.start() // this madafa is the one causing troubles
document.body.appendChild(tree)
```

**Comment by yoshuawuyts** [comment]
@sospedra hmm, odd - could you share your browser version, choo version, node version and npm version? Thanks!

**Comment by MattMcFarland** [comment]
I have had this problem too unless I use app.model() - I thought that was expected!!

**Comment by yoshuawuyts** [comment]
woah, yeah that's no good - def not expected

**Comment by sospedra** [comment]
Chrome 51 && Firefox DevEd 44.0
Choo 3.2.0
node 4.2.1
npm 2.14.7
budo 8.3.0
browserify 13.1.0

And, using .model didn't work :/

**Comment by sospedra** [comment]
so?

**Comment by timwis** [comment]
Hey @sospedra, it looks like you used an object instead of an array in the router.

``` javascript
app.router((route) => {
  route('/', sexyView)
})
// should be
app.router((route) => [
  route('/', sexyView)
])
```

I reproduced your issue and fixing this resolved it. Hope that helps!

**Comment by goto-bus-stop** [comment]
This tutorial no longer exists, so I think this can be closed. Thanks!
