### ISSUE TITLE
the way it looks

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/workshop-choo#25]
The gcloud documentation is probably doing a good job; we could totes copy their design but change the font and make it like more pink. For reference:

<img width="1278" alt="screen shot 2016-08-10 at 15 35 31" src="https://cloud.githubusercontent.com/assets/2467194/17555582/56baedfe-5f10-11e6-9ed9-b1eceefb5cd3.png">

<img width="488" alt="screen shot 2016-08-10 at 15 36 17" src="https://cloud.githubusercontent.com/assets/2467194/17555588/5c2338aa-5f10-11e6-9d84-be7245467efc.png">

especially the versioning + links to stackoverflow / github / npm would be grand

**Comment by MattMcFarland** [comment]
I think there is a choo documentation project over on the awesome choo repo. I would link but not so good with the mobile!

**Comment by MattMcFarland** [comment]
Whoops! I mean to say there is a doc generator made with choo that looks similar!

**Comment by yoshuawuyts** [comment]
oh yeah, we're using it here but haven't deployed it yet - should config the styling a lil tho to make it fit in with the rest of the project C:

**Comment by yoshuawuyts** [comment]
okay, closing this for now as we've moved to gitbook :sparkles: yay for not managing deploys
