### ISSUE TITLE
bel or yo-yo?

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/workshop-choo#39]
https://yoshuawuyts.gitbooks.io/choo/content/03_elements/01_html.html says that `choo` uses `bel` under the hood. But `bel` is not present in [package.json](https://github.com/yoshuawuyts/choo/blob/0bd73e88afe7dbe28ed1a6bd3a1fc1cfe0ea1745/package.json). Isn't it using `yo-yo`, which in turn depends on `bel`?

**Comment by yoshuawuyts** [comment]
Heya, yeah you're right. But inside `yo-yo` the `html` call is simply
calling `bel` directly so figured it was similar.
Do you find this confusing? Do you reckon we should mention `yo-yo` in that
sentence

**Comment by zeke** [comment]
>  Do you reckon we should mention `yo-yo` in that sentence

👍 I can open a PR for that

**Comment by yoshuawuyts** [comment]
That would be neat, thanks!

**Comment by yoshuawuyts** [comment]
lol, seems like my emails from a few days ago are finally coming through 😓

**Comment by zeke** [comment]
`¯\_(ツ)_/¯`
