### ISSUE TITLE
use minidocs

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/workshop-choo#6]
use https://github.com/freeman-lab/minidocs and create a build workflow; perhaps auto-publish too

**Comment by sethvincent** [comment]
I can help with this! Working on a branch now to get minidocs set up.

**Comment by yoshuawuyts** [comment]
@sethvincent heaps rad! :D

**Comment by yoshuawuyts** [comment]
Ah so #7 was added; probably need to publish this to GH pages too sometime and more work

**Comment by yoshuawuyts** [comment]
Closing this for now as we're using gitbook. We'll probs want to move to a self-hosted thing later (yay, minidocs!), but this is easier for now :sparkles:
