### ISSUE TITLE
Alice should have fun 3 times

### ISSUE THREAD

**Issue by delaguilaluis** [yoshuawuyts/workshop-choo#91]
In the example where Alice is having fun, the `sentence` function is called 3 times, but the output shows only one sentence.

**Comment by toddself** [comment]
Thats because Alice got tired and wanted to go home early. She does have to get up at 6 every day to fight the patriarchy!

**Comment by delaguilaluis** [comment]
That was my first thought... thanks for confirming, let's close this issue then. (?)

**Comment by louiscenter** [comment]
Thanks for reporting this, and for your patience ^__^

Would you be interested in submitting a PR for this? That would be super helpful ✨

**Comment by louiscenter** [comment]
@delaguilaluis thanks for reporting this, and for your patience ^__^

Would you be interested in submitting a PR for this? That would be super helpful ✨

**Comment by delaguilaluis** [comment]
Sure thing! I didn't do it because I didn't knew if calling the `sentence` function three times was your intention.

I mean, should I change it to only call sentence once or should I change it to show three logs for it?

**Comment by louiscenter** [comment]
@delaguilaluis I think we should change it to show three logs ^__^

**Comment by delaguilaluis** [comment]
Your wish is my command.

**Comment by louiscenter** [comment]
Thank you!
