### ISSUE TITLE
double check on adorable GIF licensing

### ISSUE THREAD

**Issue by cdaringe** [yoshuawuyts/workshop-choo#97]
hi friends,

i wanted to make sure that i can use your super awesome little animated critter GIFs.  the project says MIT, but wasn't sure included the imgs.

they are fun, and i wanted to use them as loading animations on my recent choo app.  where'd they come from, btw?

thx!

**Comment by yoshuawuyts** [comment]
@louiscenter ping, think this one's for you

**Comment by louiscenter** [comment]
@cdaringe thanks for patience. somehow missed this issue thread completely :<

I bought this assets from a sprite store, so I'd suggest grabbing a license of your own if you'd like to use them too: https://www.scirra.com/store/2d-game-sprites/game-animals-volume-2-3249
